spring.application.name=EmailMS
spring.datasource.url=jdbc:postgresql://localhost:5434/emailms
spring.datasource.username=emailms_user
spring.datasource.password=email
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.rabbitmq.adresses=amqps://kllfmgma:SVKhpZM31WD61v4zqmb0mlupwg8WQoWn@jackal.rmq.cloudamqp.com/kllfmgma
broker.queue.name